-- Desactivar temporalmente las verificaciones de claves foráneas
SET FOREIGN_KEY_CHECKS = 0;

-- Borrar datos de las tablas dependientes primero
DELETE FROM DETALLE_PEDIDO;
DELETE FROM CANJES;
DELETE FROM LOYALTY_TRANSACTIONS;
DELETE FROM PAGOS;
DELETE FROM PEDIDOS;

-- Luego borrar tablas independientes
DELETE FROM PRODUCTOS;
DELETE FROM PROVEEDORES;
DELETE FROM EMPLEADOS;
DELETE FROM CLIENTES;
DELETE FROM RECOMPENSAS;
DELETE FROM INVENTARIO;

-- Reiniciar AUTO_INCREMENT de todas las tablas
ALTER TABLE CLIENTES AUTO_INCREMENT = 1;
ALTER TABLE EMPLEADOS AUTO_INCREMENT = 1;
ALTER TABLE PROVEEDORES AUTO_INCREMENT = 1;
ALTER TABLE PRODUCTOS AUTO_INCREMENT = 1;
ALTER TABLE PEDIDOS AUTO_INCREMENT = 1;
ALTER TABLE DETALLE_PEDIDO AUTO_INCREMENT = 1;
ALTER TABLE INVENTARIO AUTO_INCREMENT = 1;
ALTER TABLE LOYALTY_TRANSACTIONS AUTO_INCREMENT = 1;
ALTER TABLE RECOMPENSAS AUTO_INCREMENT = 1;
ALTER TABLE CANJES AUTO_INCREMENT = 1;
ALTER TABLE PAGOS AUTO_INCREMENT = 1;

-- Reactivar la verificación de claves foráneas
SET FOREIGN_KEY_CHECKS = 1;
