SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM DETALLE_PEDIDO;
DELETE FROM CANJES;
DELETE FROM LOYALTY_TRANSACTIONS;
DELETE FROM PAGOS;
DELETE FROM PEDIDOS;

DELETE FROM PRODUCTOS;
DELETE FROM PROVEEDORES;
DELETE FROM EMPLEADOS;
DELETE FROM CLIENTES;
DELETE FROM RECOMPENSAS;
DELETE FROM INVENTARIO;

ALTER TABLE CLIENTES AUTO_INCREMENT = 1;
ALTER TABLE EMPLEADOS AUTO_INCREMENT = 1;
ALTER TABLE PROVEEDORES AUTO_INCREMENT = 1;
ALTER TABLE PRODUCTOS AUTO_INCREMENT = 1;
ALTER TABLE PEDIDOS AUTO_INCREMENT = 1;
ALTER TABLE DETALLE_PEDIDO AUTO_INCREMENT = 1;
ALTER TABLE INVENTARIO AUTO_INCREMENT = 1;
ALTER TABLE LOYALTY_TRANSACTIONS AUTO_INCREMENT = 1;
ALTER TABLE RECOMPENSAS AUTO_INCREMENT = 1;
ALTER TABLE CANJES AUTO_INCREMENT = 1;
ALTER TABLE PAGOS AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
