-- ======================================================
-- PROYECTO: DailyDose - Gestión de Cafetería y Fidelización
-- SISTEMA GESTOR: MySQL
-- ======================================================

-- 1. GESTIÓN DE ACCESO Y ROLES
-- ------------------------------------------------------
CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50),
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL, -- Almacena el hash
    ROL ENUM('CLIENTE', 'EMPLEADO', 'ADMIN') NOT NULL,
    CAMBIAR_PASSWORD TINYINT(1) DEFAULT 0,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT UNIQUE,
    TELEFONO VARCHAR(15),
    PUNTOS INT DEFAULT 0,
    CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT UNIQUE,
    PUESTO VARCHAR(50),
    SALARIO DECIMAL(8,2),
    TURNO VARCHAR(20),
    FECHA_CONTRATACION DATE,
    CONSTRAINT FK_EMPLEADO_USUARIO FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE TURNOS (
    ID_TURNO INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL,
    DIA DATE NOT NULL,
    TURNO ENUM('MAÑANA', 'TARDE') NOT NULL,
    CONSTRAINT FK_TURNO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) 
        REFERENCES EMPLEADOS(ID_EMPLEADO) ON DELETE CASCADE,
    CONSTRAINT UQ_EMPLEADO_DIA UNIQUE (ID_EMPLEADO, DIA)
);

-- =========================
-- TABLA NOTIFICACIONES
-- =========================
CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT, -- Destinatario de la notificación
    TITULO VARCHAR(100) NOT NULL,
    MENSAJE TEXT NOT NULL,
    TIPO ENUM('PEDIDO', 'SISTEMA', 'PROMOCION', 'STOCK') DEFAULT 'SISTEMA',
    LEIDO BOOLEAN DEFAULT FALSE,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NOTIF_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

-- 2. CATÁLOGO Y PROVEEDORES
-- ------------------------------------------------------
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15),
    EMAIL VARCHAR(50),
    DIRECCION VARCHAR(100)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_CATEGORIA INT,
    ID_ESPECIALIDAD INT,
    PRECIO DECIMAL(6,2) NOT NULL,
    STOCK SMALLINT DEFAULT 0,
    ID_PROVEEDOR INT,
    RUTA_IMAGEN VARCHAR(255),
    CONSTRAINT FK_CATEGORIA_PROD FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    CONSTRAINT FK_ESPECIALIDAD FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDAD_ACTUAL(ID_ESPECIALIDAD) ON DELETE SET NULL,
    CONSTRAINT FK_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

CREATE TABLE INVENTARIO (
    ID_MOVIMIENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIPO_MOVIMIENTO ENUM('ENTRADA', 'SALIDA', 'AJUSTE'),
    CONSTRAINT FK_INVENTARIO_PROD FOREIGN KEY (ID_PRODUCTO) 
        REFERENCES PRODUCTOS(ID_PRODUCTO) ON DELETE CASCADE
);

-- 3. GESTIÓN OPERATIVA Y VENTAS
-- ------------------------------------------------------
-- =========================
-- TABLA MESAS
-- =========================
CREATE TABLE MESAS (
    ID_MESA INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_MESA INT UNIQUE NOT NULL,
    CAPACIDAD INT DEFAULT 2,
    UBICACION ENUM('INTERIOR', 'TERRAZA', 'BARRA') DEFAULT 'INTERIOR',
    ESTADO ENUM('LIBRE', 'OCUPADA', 'RESERVADA', 'MANTENIMIENTO') DEFAULT 'LIBRE'
);

CREATE TABLE ESPECIALIDAD_ACTUAL (
    ID_ESPECIALIDAD INT PRIMARY KEY AUTO_INCREMENT,
    ORIGEN_GRANO VARCHAR(100),
    NOTAS_CATA VARCHAR(150),
    TUESTE VARCHAR(50),
    METODO_FILTRO VARCHAR(50),
    DESCRIPCION_FILTRO VARCHAR(200),
    SEASONAL_NOMBRE VARCHAR(100),
    SEASONAL_DESCRIPCION VARCHAR(200),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    TOTAL DECIMAL(6,2),
    ID_EMPLEADO INT,
    ID_CLIENTE INT,
    ID_MESA INT,
    ESTADO ENUM('PENDIENTE', 'EN_PREPARACION', 'LISTO', 'ENTREGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
    CONSTRAINT FK_PEDIDO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_PEDIDO_MESA FOREIGN KEY (ID_MESA) REFERENCES MESAS(ID_MESA) ON DELETE SET NULL
);

CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT,
    ID_PRODUCTO INT,
    CANTIDAD SMALLINT NOT NULL,
    PRECIO_UNITARIO DECIMAL(6,2),
    SUBTOTAL DECIMAL(6,2),
    CONSTRAINT FK_DETALLE_PEDIDO FOREIGN KEY (ID_PEDIDO) 
        REFERENCES PEDIDOS(ID_PEDIDO) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_PROD FOREIGN KEY (ID_PRODUCTO) 
        REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE PAGOS (
    ID_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT,
    TIPO_PAGO ENUM('EFECTIVO', 'TARJETA', 'PAYPAL', 'BIZUM', 'OTRO'),
    MONTO DECIMAL(6,2),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PAGO_PEDIDO FOREIGN KEY (ID_PEDIDO) 
        REFERENCES PEDIDOS(ID_PEDIDO) ON DELETE CASCADE
);

-- 4. FIDELIZACIÓN Y RECOMPENSAS
-- ------------------------------------------------------
CREATE TABLE RECOMPENSAS (
    ID_RECOMPENSA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    COSTE_PUNTOS INT NOT NULL,
    TIPO ENUM('PRODUCTO', 'DESCUENTO') NOT NULL,
    STOCK SMALLINT DEFAULT 0,
    SOLO_EMPLEADOS BOOLEAN DEFAULT FALSE
);

CREATE TABLE CANJES (
    ID_CANJE INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    ID_RECOMPENSA INT,
    FECHA_CANJE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PUNTOS_GASTADOS INT,
    CONSTRAINT FK_CANJE_CLIENTE FOREIGN KEY (ID_CLIENTE) 
        REFERENCES CLIENTES(ID_CLIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_CANJE_RECOMPENSA FOREIGN KEY (ID_RECOMPENSA) 
        REFERENCES RECOMPENSAS(ID_RECOMPENSA)
);

CREATE TABLE HISTORIAL_PUNTOS (
    ID_MOVIMIENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    TIPO_MOVIMIENTO ENUM('SUMA', 'RESTA') NOT NULL,
    CANTIDAD INT NOT NULL,
    MOTIVO VARCHAR(255),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_HISTORIAL_CLIENTE FOREIGN KEY (ID_CLIENTE) 
        REFERENCES CLIENTES(ID_CLIENTE) ON DELETE CASCADE
);
