/*VISTAS*/

CREATE OR REPLACE VIEW v_estado_sala AS
SELECT 
    m.ID_MESA,
    m.NUMERO_MESA,
    m.CAPACIDAD,
    m.UBICACION,
    m.ESTADO AS ESTADO_MESA,
    p.ID_PEDIDO,
    p.TOTAL AS TOTAL_PEDIDO,
    p.ESTADO AS ESTADO_PEDIDO,
    u_emp.NOMBRE AS NOMBRE_CAMARERO
FROM MESAS m
LEFT JOIN PEDIDOS p ON m.ID_MESA = p.ID_MESA AND p.ESTADO NOT IN ('ENTREGADO', 'CANCELADO')
LEFT JOIN EMPLEADOS e ON p.ID_EMPLEADO = e.ID_EMPLEADO
LEFT JOIN USUARIOS u_emp ON e.ID_USUARIO = u_emp.ID_USUARIO;


CREATE OR REPLACE VIEW v_catalogo_menu AS
SELECT 
    p.ID_PRODUCTO,
    p.NOMBRE AS NOMBRE_PRODUCTO,
    p.PRECIO,
    p.STOCK,
    p.RUTA_IMAGEN,
    c.NOMBRE_CATEGORIA,
    ea.ORIGEN_GRANO,
    ea.NOTAS_CATA,
    ea.TUESTE,
    ea.METODO_FILTRO
FROM PRODUCTOS p
JOIN CATEGORIAS c ON p.ID_CATEGORIA = c.ID_CATEGORIA
LEFT JOIN ESPECIALIDAD_ACTUAL ea ON p.ID_ESPECIALIDAD = ea.ID_ESPECIALIDAD;


CREATE OR REPLACE VIEW v_perfil_fidelizacion AS
SELECT 
    c.ID_CLIENTE,
    u.ID_USUARIO,
    u.NOMBRE,
    u.APELLIDOS,
    u.EMAIL,
    c.TELEFONO,
    c.PUNTOS AS PUNTOS_ACTUALES,
    u.FECHA_REGISTRO
FROM CLIENTES c
JOIN USUARIOS u ON c.ID_USUARIO = u.ID_USUARIO;


CREATE OR REPLACE VIEW v_alertas_stock AS
SELECT 
    p.ID_PRODUCTO,
    p.NOMBRE AS NOMBRE_PRODUCTO,
    p.STOCK AS STOCK_ACTUAL,
    c.NOMBRE_CATEGORIA,
    prov.NOMBRE AS NOMBRE_PROVEEDOR,
    prov.TELEFONO AS TELEFONO_PROVEEDOR
FROM PRODUCTOS p
JOIN CATEGORIAS c ON p.ID_CATEGORIA = c.ID_CATEGORIA
JOIN PROVEEDORES prov ON p.ID_PROVEEDOR = prov.ID_PROVEEDOR
WHERE p.STOCK <= 10
ORDER BY p.STOCK ASC;


CREATE OR REPLACE VIEW v_resumen_caja_diario AS
SELECT 
    DATE(FECHA) AS FECHA_DIA,
    TIPO_PAGO,
    SUM(MONTO) AS TOTAL_RECAUDADO,
    COUNT(ID_PAGO) AS NUMERO_VENTAS
FROM PAGOS
GROUP BY DATE(FECHA), TIPO_PAGO
ORDER BY FECHA_DIA DESC;


CREATE OR REPLACE VIEW v_ranking_clientes_vip AS
SELECT 
    c.ID_CLIENTE,
    u.NOMBRE,
    u.APELLIDOS,
    u.EMAIL,
    c.PUNTOS AS PUNTOS_ACUMULADOS
FROM CLIENTES c
JOIN USUARIOS u ON c.ID_USUARIO = u.ID_USUARIO
ORDER BY c.PUNTOS DESC;


CREATE OR REPLACE VIEW v_rendimiento_camareros AS
SELECT 
    e.ID_EMPLEADO,
    u.NOMBRE AS NOMBRE_EMPLEADO,
    u.APELLIDOS AS APELLIDOS_EMPLEADO,
    e.PUESTO,
    COUNT(p.ID_PEDIDO) AS TOTAL_PEDIDOS_ATENDIDOS,
    SUM(p.TOTAL) AS FACTURACION_TOTAL
FROM EMPLEADOS e
JOIN USUARIOS u ON e.ID_USUARIO = u.ID_USUARIO
LEFT JOIN PEDIDOS p ON e.ID_EMPLEADO = p.ID_EMPLEADO AND p.ESTADO = 'ENTREGADO'
GROUP BY e.ID_EMPLEADO
ORDER BY FACTURACION_TOTAL DESC;


CREATE OR REPLACE VIEW v_carta_publica AS
SELECT 
    p.ID_PRODUCTO,
    p.NOMBRE AS NOMBRE_PRODUCTO,
    p.PRECIO,
    p.RUTA_IMAGEN,
    c.NOMBRE_CATEGORIA,
    ea.ORIGEN_GRANO,
    ea.NOTAS_CATA,
    ea.TUESTE,
    ea.METODO_FILTRO,
    ea.SEASONAL_NAME
FROM PRODUCTOS p
JOIN CATEGORIAS c ON p.ID_CATEGORIA = c.ID_CATEGORIA
LEFT JOIN ESPECIALIDAD_ACTUAL ea ON p.ID_ESPECIALIDAD = ea.ID_ESPECIALIDAD
WHERE p.STOCK > 0 -- Regla de negocio: Solo lo disponible en tiempo real
ORDER BY c.ID_CATEGORIA ASC, p.NOMBRE ASC;


